name: grocery
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter



  cupertino_icons: ^1.0.8

  # ðŸŒ HTTP (PHP API Integration)
  http: ^1.2.0

  # ðŸ’³ PAYMENT GATEWAY (Razorpay)
  razorpay_flutter: ^1.3.7

  # ðŸ” LOGIN, SIGNUP, CART, SESSION
  shared_preferences: ^2.3.2

  # ðŸ–¼ IMAGE PICK & CROP (Profile / Products)
  image_picker: ^1.2.1
  image_cropper: ^11.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.4.1





  flutter_lints: ^2.0.3

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icon/app_icon.png

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Medium.ttf
        - asset: assets/fonts/Poppins-SemiBold.ttf
        - asset: assets/fonts/Poppins-Bold.ttf

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/app_icon.png"

flutter_native_splash:
  color: "#FFFFFF"
  image: assets/icon/app_icon.png
  android: true
  ios: true
  android_12:
    image: assets/icon/app_icon.png
    color: "#FFFFFF"


